application: APPLICATION_NAME
version: 1
runtime: php
api_version: 1

handlers:

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /img
  static_dir: img
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always

- url: /
  script: index.php
  secure: always

- url: /index.php
  script: index.php
  secure: always

- url: /validate
  script: index.php
  secure: always

- url: /mwr
  script: index.php
  secure: always

- url: /fwr
  script: index.php
  secure: always

- url: /tsn
  script: index.php
  secure: always

- url: /logout
  script: index.php
  secure: always
